### ISSUE TITLE
请问这个项目是怎么显示的wav的波形图呀

### ISSUE THREAD

**Issue by Qianzujin** [lxfly2000/wavd#1]

**Comment by lxfly2000** [comment]
按wave的数据画点连线就可以了

**Comment by Qianzujin** [comment]
![image](https://user-images.githubusercontent.com/49854479/58402019-edd0ad00-8091-11e9-85d5-cfd7b91f9fba.png)
这个哪个方法是提供wave的画点数据的呀

**Comment by Qianzujin** [comment]
我是个菜鸟，不是很懂这个画图。。。

**Comment by lxfly2000** [comment]
画图操作在main.cpp里，这个只是存wave信息用的

**Comment by Qianzujin** [comment]
好吧，就是我现在想在MFC里面读取一个WAV文件，然后画出这个WAV文件的波形图，在网上看了好多资料都不知道改怎么画，就是不知道横坐标对应的什么数据，纵坐标对应的什么数据。究竟是拿的哪部分的数据画出来的。。。。ε=(´ο｀*))) 就比如
![image](https://user-images.githubusercontent.com/49854479/58403062-62a4e680-8094-11e9-9b61-1f181a8595f0.png)这里面的值都有了以后应该怎么画出来呢，我也不知道坐标是怎么个对应方式，就是一脸迷糊，好吧，我现在在看这方面的知识，但还是没什么头绪。。。

**Comment by lxfly2000** [comment]
这个只是文件头，后面的才是数据，有数据才能画波形
